-- Seed a small, practical Portuguese exercise catalog for newly provisioned databases.
-- Idempotent and non-destructive: existing exercises and admin edits are never overwritten.
INSERT INTO public.exercise_library
  (name, muscle_group, secondary_muscles, equipment, difficulty, default_sets, default_reps, default_rest, technique_tip, source, description, steps, active)
VALUES
('Supino reto com barra','peito',ARRAY['triceps','ombros'],'Barra e banco','intermediario',3,'8-12','90s','Mantenha escápulas apoiadas e não quique a barra no peito.','fitforge_core_seed_20261009','Empurrada horizontal para peitoral, tríceps e deltoide anterior.',ARRAY['Deite no banco com os pés firmes no chão.','Segure a barra um pouco além da largura dos ombros.','Desça com controle até próximo ao meio do peito.','Empurre para cima sem perder o controle dos ombros.'],true),
('Supino inclinado com halteres','peito',ARRAY['triceps','ombros'],'Halteres e banco inclinado','intermediario',3,'8-12','90s','Use inclinação moderada e mantenha os punhos alinhados.','fitforge_core_seed_20261009','Ênfase na porção clavicular do peitoral.',ARRAY['Ajuste o banco em inclinação moderada.','Inicie com halteres ao lado do peito.','Empurre para cima sem bater os halteres.','Desça lentamente até amplitude confortável.'],true),
('Crucifixo na máquina','peito',ARRAY['ombros'],'Peck deck','iniciante',3,'10-15','60s','Mantenha leve flexão dos cotovelos e evite alongamento doloroso.','fitforge_core_seed_20261009','Isolamento do peitoral com trajetória guiada.',ARRAY['Ajuste o assento para alinhar os braços ao peito.','Aproxime os braços sem usar impulso.','Contraia o peitoral brevemente.','Retorne devagar até amplitude confortável.'],true),
('Puxada frontal na polia','costas',ARRAY['biceps','antebraco'],'Polia alta e barra','iniciante',3,'8-12','90s','Puxe em direção à parte superior do peito sem balançar o tronco.','fitforge_core_seed_20261009','Puxada vertical para dorsais e flexores do cotovelo.',ARRAY['Sente e fixe as coxas sob o apoio.','Segure a barra um pouco além dos ombros.','Puxe os cotovelos para baixo.','Retorne controlando a subida da barra.'],true),
('Remada baixa na polia','costas',ARRAY['biceps','trapezio'],'Polia baixa e triângulo','iniciante',3,'8-12','90s','Evite arredondar a lombar ou transformar o movimento em balanço.','fitforge_core_seed_20261009','Remada horizontal para costas e musculatura escapular.',ARRAY['Sente com coluna neutra e joelhos levemente flexionados.','Puxe o acessório em direção ao abdômen.','Aproxime as escápulas sem elevar os ombros.','Estenda os braços lentamente.'],true),
('Remada curvada com barra','costas',ARRAY['biceps','lombar','trapezio'],'Barra','avancado',3,'6-10','120s','Mantenha coluna neutra e reduza a carga se perder a posição.','fitforge_core_seed_20261009','Remada composta para dorsais, romboides e estabilizadores do tronco.',ARRAY['Afaste os pés na largura do quadril e flexione levemente os joelhos.','Incline o tronco mantendo a coluna neutra.','Puxe a barra em direção ao abdômen.','Desça com controle sem arredondar as costas.'],true),
('Levantamento terra romeno','posterior',ARRAY['gluteos','lombar'],'Barra ou halteres','intermediario',3,'8-12','120s','Faça a dobradiça de quadril e mantenha a carga próxima às pernas.','fitforge_core_seed_20261009','Exercício de cadeia posterior com ênfase em posteriores e glúteos.',ARRAY['Fique em pé com a carga à frente das coxas.','Leve o quadril para trás com joelhos levemente flexionados.','Desça até sentir alongamento sem perder a coluna neutra.','Estenda o quadril para voltar à posição inicial.'],true),
('Agachamento livre','quadriceps',ARRAY['gluteos','posterior','abdomen'],'Barra e rack','avancado',3,'6-10','120s','Use amplitude controlada e carga compatível com sua mobilidade e técnica.','fitforge_core_seed_20261009','Movimento composto para quadríceps, glúteos e tronco.',ARRAY['Posicione a barra com segurança e firme os pés no chão.','Inspire e desça flexionando quadris e joelhos.','Mantenha os pés apoiados e o tronco estável.','Suba empurrando o chão sem perder o alinhamento.'],true),
('Leg press 45 graus','quadriceps',ARRAY['gluteos','posterior'],'Leg press','iniciante',3,'10-15','90s','Não bloqueie os joelhos e não deixe a lombar arredondar no fundo.','fitforge_core_seed_20261009','Exercício guiado para quadríceps e glúteos.',ARRAY['Ajuste o encosto e coloque os pés na plataforma.','Destrave o equipamento mantendo o controle.','Desça até amplitude que preserve a lombar apoiada.','Empurre a plataforma sem travar os joelhos.'],true),
('Cadeira extensora','quadriceps',ARRAY[]::text[],'Máquina extensora','iniciante',3,'10-15','60s','Evite chutar a carga e controle a descida.','fitforge_core_seed_20261009','Isolamento do quadríceps.',ARRAY['Ajuste o eixo da máquina próximo ao joelho.','Estenda os joelhos sem impulso.','Contraia o quadríceps brevemente.','Retorne lentamente.'],true),
('Mesa flexora','posterior',ARRAY['panturrilha'],'Máquina flexora','iniciante',3,'10-15','60s','Mantenha o quadril apoiado e não use balanço.','fitforge_core_seed_20261009','Flexão de joelhos para posteriores de coxa.',ARRAY['Ajuste o rolo acima dos calcanhares.','Flexione os joelhos contra a resistência.','Pause sem tirar o quadril do apoio.','Retorne devagar.'],true),
('Elevação pélvica','gluteos',ARRAY['posterior','quadriceps'],'Banco e barra ou máquina','intermediario',3,'8-12','90s','Finalize com extensão do quadril sem hiperestender a lombar.','fitforge_core_seed_20261009','Extensão de quadril com ênfase nos glúteos.',ARRAY['Apoie a parte superior das costas no banco.','Posicione os pés firmes e a carga sobre o quadril com proteção.','Eleve o quadril até alinhar tronco e coxas.','Desça com controle.'],true),
('Abdução de quadril na máquina','gluteos',ARRAY[]::text[],'Máquina abdutora','iniciante',3,'12-20','60s','Evite impulsos e mantenha a pelve estável.','fitforge_core_seed_20261009','Trabalho dos abdutores do quadril, incluindo glúteo médio.',ARRAY['Sente com as costas apoiadas.','Posicione as pernas contra as almofadas.','Afaste os joelhos de forma controlada.','Retorne sem deixar os pesos baterem.'],true),
('Desenvolvimento com halteres','ombros',ARRAY['triceps'],'Halteres e banco','intermediario',3,'8-12','90s','Não arqueie excessivamente a lombar; use amplitude confortável.','fitforge_core_seed_20261009','Empurrada vertical para deltoides e tríceps.',ARRAY['Sente ou fique em pé com o tronco firme.','Inicie com halteres próximos à altura dos ombros.','Empurre para cima sem bater os halteres.','Desça de forma controlada.'],true),
('Elevação lateral com halteres','ombros',ARRAY['trapezio'],'Halteres','iniciante',3,'12-20','60s','Eleve sem impulso e sem encolher os ombros.','fitforge_core_seed_20261009','Isolamento do deltoide lateral.',ARRAY['Fique em pé com halteres ao lado do corpo.','Eleve os braços lateralmente com cotovelos levemente flexionados.','Pare aproximadamente na altura dos ombros.','Desça lentamente.'],true),
('Face pull na polia','ombros',ARRAY['costas','trapezio'],'Polia alta e corda','iniciante',3,'12-15','60s','Puxe em direção ao rosto com cotovelos abertos e sem dor.','fitforge_core_seed_20261009','Exercício para deltoide posterior e controle escapular.',ARRAY['Prenda a corda na polia alta.','Puxe em direção ao rosto separando as pontas da corda.','Mantenha o tronco estável.','Retorne lentamente.'],true),
('Rosca direta com barra','biceps',ARRAY['antebraco'],'Barra reta ou W','iniciante',3,'8-12','60s','Mantenha cotovelos próximos ao tronco e evite balançar.','fitforge_core_seed_20261009','Flexão de cotovelos para bíceps.',ARRAY['Fique em pé segurando a barra com palmas para cima.','Flexione os cotovelos mantendo os braços junto ao corpo.','Aproxime a barra do tronco sem inclinar para trás.','Desça lentamente.'],true),
('Rosca martelo','biceps',ARRAY['antebraco'],'Halteres','iniciante',3,'10-15','60s','Mantenha os punhos neutros e não use impulso.','fitforge_core_seed_20261009','Rosca com pegada neutra para bíceps e braquial.',ARRAY['Segure os halteres com palmas voltadas uma para a outra.','Flexione os cotovelos sem mover os ombros.','Suba até amplitude confortável.','Desça controlando a carga.'],true),
('Tríceps na polia com corda','triceps',ARRAY[]::text[],'Polia alta e corda','iniciante',3,'10-15','60s','Mantenha os cotovelos junto ao tronco.','fitforge_core_seed_20261009','Extensão de cotovelos para tríceps.',ARRAY['Prenda a corda na polia alta.','Mantenha os cotovelos flexionados junto ao corpo.','Estenda os braços e separe levemente as pontas da corda.','Retorne sem mover os ombros.'],true),
('Tríceps francês com halter','triceps',ARRAY['ombros'],'Halter','intermediario',3,'10-12','60s','Use carga controlável e evite desconforto nos cotovelos.','fitforge_core_seed_20261009','Extensão de cotovelos acima da cabeça.',ARRAY['Segure um halter acima da cabeça com as duas mãos.','Flexione os cotovelos levando a carga atrás da cabeça.','Estenda os cotovelos sem abrir excessivamente os braços.','Repita com controle.'],true),
('Prancha abdominal','abdomen',ARRAY['gluteos','ombros'],'Peso corporal','iniciante',3,'20-45s','Mantenha o corpo alinhado e respire sem prender o ar.','fitforge_core_seed_20261009','Isometria para estabilidade do tronco.',ARRAY['Apoie antebraços e pontas dos pés no chão.','Alinhe cabeça, tronco e quadris.','Contraia abdômen e glúteos mantendo a respiração.','Encerre antes de perder o alinhamento.'],true),
('Abdominal crunch','abdomen',ARRAY[]::text[],'Peso corporal ou colchonete','iniciante',3,'12-20','45s','Faça flexão controlada do tronco sem puxar o pescoço.','fitforge_core_seed_20261009','Flexão do tronco com ênfase no reto abdominal.',ARRAY['Deite de costas com joelhos flexionados.','Apoie as mãos levemente junto à cabeça ou no peito.','Eleve as escápulas aproximando as costelas da pelve.','Retorne devagar.'],true),
('Panturrilha em pé','panturrilha',ARRAY[]::text[],'Máquina ou halteres','iniciante',4,'10-20','45s','Use amplitude completa e pause brevemente no topo.','fitforge_core_seed_20261009','Elevação dos calcanhares para gastrocnêmio e sóleo.',ARRAY['Fique com a parte anterior dos pés apoiada.','Desça os calcanhares até alongamento confortável.','Eleve os calcanhares o máximo controlável.','Pause e desça lentamente.'],true),
('Encolhimento com halteres','trapezio',ARRAY['ombros'],'Halteres','iniciante',3,'10-15','60s','Eleve os ombros verticalmente sem girá-los.','fitforge_core_seed_20261009','Elevação escapular para trapézio superior.',ARRAY['Fique em pé segurando halteres ao lado do corpo.','Eleve os ombros em direção às orelhas.','Pause brevemente no topo.','Desça de forma controlada.'],true),
('Extensão lombar no banco','lombar',ARRAY['gluteos','posterior'],'Banco romano','intermediario',2,'10-15','60s','Use amplitude curta e neutra, sem hiperextender a coluna.','fitforge_core_seed_20261009','Fortalecimento dos extensores do tronco e quadril.',ARRAY['Ajuste o apoio abaixo da linha do quadril.','Mantenha a coluna neutra e cruze os braços.','Incline o tronco de forma controlada.','Retorne até alinhar o corpo, sem hiperextensão.'],true),
('Rosca inversa','antebraco',ARRAY['biceps'],'Barra W ou barra reta','intermediario',3,'10-15','60s','Use carga moderada e mantenha os punhos alinhados.','fitforge_core_seed_20261009','Flexão de cotovelo com pegada pronada para antebraços.',ARRAY['Segure a barra com palmas voltadas para baixo.','Flexione os cotovelos mantendo-os junto ao corpo.','Suba sem balançar o tronco.','Desça lentamente.'],true),
('Agachamento goblet','quadriceps',ARRAY['gluteos','abdomen'],'Halter ou kettlebell','iniciante',3,'8-12','90s','Mantenha o peso próximo ao peito e os pés firmes.','fitforge_core_seed_20261009','Agachamento com carga frontal para quadríceps e glúteos.',ARRAY['Segure um halter junto ao peito.','Afaste os pés em posição confortável.','Agache mantendo o tronco firme e os joelhos alinhados aos pés.','Suba empurrando o chão.'],true),
('Afundo com halteres','quadriceps',ARRAY['gluteos','posterior'],'Halteres','intermediario',3,'8-12 por lado','90s','Dê um passo estável e mantenha o joelho alinhado com o pé.','fitforge_core_seed_20261009','Exercício unilateral para quadríceps e glúteos.',ARRAY['Fique em pé segurando halteres ao lado do corpo.','Dê um passo à frente e flexione os joelhos.','Desça mantendo o tronco estável.','Empurre o chão para retornar e alterne os lados.'],true),
('Puxada alta com pegada neutra','costas',ARRAY['biceps'],'Polia alta e pegador neutro','iniciante',3,'8-12','90s','Evite jogar o tronco para trás durante a puxada.','fitforge_core_seed_20261009','Variação de puxada vertical para dorsais.',ARRAY['Sente com as coxas fixadas.','Segure o pegador com palmas voltadas uma para a outra.','Puxe os cotovelos para baixo.','Retorne lentamente.'],true),
('Remada unilateral com halter','costas',ARRAY['biceps','antebraco'],'Halter e banco','iniciante',3,'8-12 por lado','75s','Mantenha o tronco estável e evite girar o quadril.','fitforge_core_seed_20261009','Remada unilateral para dorsais e musculatura escapular.',ARRAY['Apoie uma mão e um joelho no banco.','Mantenha a coluna neutra e o halter abaixo do ombro.','Puxe o cotovelo em direção ao quadril.','Desça controlando e troque o lado.'],true),
('Flexão de braços','peito',ARRAY['triceps','ombros'],'Peso corporal','iniciante',3,'6-15','60s','Mantenha tronco alinhado e use apoio elevado se necessário.','fitforge_core_seed_20261009','Empurrada horizontal com peso corporal.',ARRAY['Apoie as mãos um pouco além da largura dos ombros.','Alinhe cabeça, tronco e pernas.','Flexione os cotovelos descendo com controle.','Empurre o chão até estender os braços sem perder o alinhamento.'],true),
('Caminhada na esteira','cardio',ARRAY['quadriceps','panturrilha'],'Esteira','iniciante',1,'10-30 min','—','Ajuste velocidade e inclinação para conseguir manter conversa.','fitforge_core_seed_20261009','Atividade aeróbica de baixo impacto ajustável ao condicionamento.',ARRAY['Suba na esteira parada e prenda o clip de segurança.','Comece em velocidade confortável.','Aumente gradualmente conforme tolerância.','Reduza a velocidade antes de descer.'],true)
ON CONFLICT (name, muscle_group) DO NOTHING;
