-- Seed a core Portuguese exercise catalog for fresh databases.
-- Idempotent and non-destructive: existing exercises/admin edits are not overwritten.
INSERT INTO public.exercise_library
(name,muscle_group,equipment,difficulty,default_sets,default_reps,default_rest,source,description,steps,active)
VALUES
('Supino reto com barra','peito','Barra e banco','intermediario',3,'8-12','90s','fitforge_core_seed_20261009','Empurrada horizontal para peitoral e tríceps.',ARRAY['Pés firmes e escápulas apoiadas.','Desça a barra com controle até próximo ao peito.','Empurre sem perder o alinhamento dos ombros.'],true),
('Supino inclinado com halteres','peito','Halteres e banco inclinado','intermediario',3,'8-12','90s','fitforge_core_seed_20261009','Ênfase na porção superior do peitoral.',ARRAY['Ajuste o banco em inclinação moderada.','Desça os halteres até amplitude confortável.','Empurre para cima sem bater os halteres.'],true),
('Crucifixo na máquina','peito','Peck deck','iniciante',3,'10-15','60s','fitforge_core_seed_20261009','Isolamento do peitoral com trajetória guiada.',ARRAY['Ajuste o assento.','Aproxime os braços sem impulso.','Retorne devagar.'],true),
('Flexão de braços','peito','Peso corporal','iniciante',3,'6-15','60s','fitforge_core_seed_20261009','Empurrada horizontal com peso corporal.',ARRAY['Apoie as mãos um pouco além dos ombros.','Desça mantendo o tronco alinhado.','Empurre o chão para retornar.'],true),
('Puxada frontal na polia','costas','Polia alta e barra','iniciante',3,'8-12','90s','fitforge_core_seed_20261009','Puxada vertical para dorsais e bíceps.',ARRAY['Fixe as coxas sob o apoio.','Puxe os cotovelos para baixo.','Retorne lentamente.'],true),
('Remada baixa na polia','costas','Polia baixa e triângulo','iniciante',3,'8-12','90s','fitforge_core_seed_20261009','Remada horizontal para costas e escápulas.',ARRAY['Sente com coluna neutra.','Puxe o acessório em direção ao abdômen.','Estenda os braços com controle.'],true),
('Remada curvada com barra','costas','Barra','avancado',3,'6-10','120s','fitforge_core_seed_20261009','Remada composta para dorsais e musculatura escapular.',ARRAY['Incline o tronco mantendo coluna neutra.','Puxe a barra em direção ao abdômen.','Desça sem arredondar as costas.'],true),
('Agachamento livre','quadriceps','Barra e rack','avancado',3,'6-10','120s','fitforge_core_seed_20261009','Movimento composto para quadríceps e glúteos.',ARRAY['Posicione a barra com segurança.','Desça flexionando quadris e joelhos.','Suba mantendo pés apoiados e tronco estável.'],true),
('Agachamento goblet','quadriceps','Halter ou kettlebell','iniciante',3,'8-12','90s','fitforge_core_seed_20261009','Agachamento com carga frontal.',ARRAY['Segure o peso junto ao peito.','Agache com joelhos alinhados aos pés.','Suba empurrando o chão.'],true),
('Leg press 45 graus','quadriceps','Leg press','iniciante',3,'10-15','90s','fitforge_core_seed_20261009','Exercício guiado para quadríceps e glúteos.',ARRAY['Ajuste o encosto e apoie os pés.','Desça até manter a lombar apoiada.','Empurre sem travar os joelhos.'],true),
('Cadeira extensora','quadriceps','Máquina extensora','iniciante',3,'10-15','60s','fitforge_core_seed_20261009','Isolamento do quadríceps.',ARRAY['Ajuste o eixo próximo ao joelho.','Estenda os joelhos com controle.','Retorne lentamente.'],true),
('Mesa flexora','posterior','Máquina flexora','iniciante',3,'10-15','60s','fitforge_core_seed_20261009','Flexão de joelhos para posteriores de coxa.',ARRAY['Ajuste o rolo acima dos calcanhares.','Flexione os joelhos mantendo o quadril apoiado.','Retorne devagar.'],true),
('Levantamento terra romeno','posterior','Barra ou halteres','intermediario',3,'8-12','120s','fitforge_core_seed_20261009','Exercício de cadeia posterior.',ARRAY['Comece em pé com a carga junto às coxas.','Leve o quadril para trás mantendo coluna neutra.','Estenda o quadril para retornar.'],true),
('Elevação pélvica','gluteos','Banco e barra ou máquina','intermediario',3,'8-12','90s','fitforge_core_seed_20261009','Extensão de quadril com ênfase nos glúteos.',ARRAY['Apoie as costas no banco.','Eleve o quadril até alinhar tronco e coxas.','Desça com controle.'],true),
('Desenvolvimento com halteres','ombros','Halteres','intermediario',3,'8-12','90s','fitforge_core_seed_20261009','Empurrada vertical para deltoides e tríceps.',ARRAY['Inicie com halteres à altura dos ombros.','Empurre para cima com tronco firme.','Desça lentamente.'],true),
('Elevação lateral com halteres','ombros','Halteres','iniciante',3,'12-20','60s','fitforge_core_seed_20261009','Isolamento do deltoide lateral.',ARRAY['Segure os halteres ao lado do corpo.','Eleve os braços até perto da altura dos ombros.','Desça lentamente.'],true),
('Rosca direta com barra','biceps','Barra reta ou W','iniciante',3,'8-12','60s','fitforge_core_seed_20261009','Flexão de cotovelos para bíceps.',ARRAY['Segure a barra com palmas para cima.','Flexione os cotovelos sem balançar o tronco.','Desça com controle.'],true),
('Rosca martelo','biceps','Halteres','iniciante',3,'10-15','60s','fitforge_core_seed_20261009','Rosca com pegada neutra para bíceps e braquial.',ARRAY['Segure halteres com palmas voltadas uma para a outra.','Flexione os cotovelos sem mover os ombros.','Desça lentamente.'],true),
('Tríceps na polia com corda','triceps','Polia alta e corda','iniciante',3,'10-15','60s','fitforge_core_seed_20261009','Extensão de cotovelos para tríceps.',ARRAY['Mantenha os cotovelos junto ao corpo.','Estenda os braços e abra levemente a corda.','Retorne com controle.'],true),
('Prancha abdominal','abdomen','Peso corporal','iniciante',3,'20-45s','45s','fitforge_core_seed_20261009','Isometria para estabilidade do tronco.',ARRAY['Apoie antebraços e pontas dos pés.','Alinhe cabeça, tronco e quadris.','Mantenha a posição sem perder o alinhamento.'],true),
('Abdominal crunch','abdomen','Peso corporal ou colchonete','iniciante',3,'12-20','45s','fitforge_core_seed_20261009','Flexão controlada do tronco para abdômen.',ARRAY['Deite com joelhos flexionados.','Eleve as escápulas com controle.','Retorne lentamente.'],true),
('Panturrilha em pé','panturrilha','Máquina ou halteres','iniciante',4,'10-20','45s','fitforge_core_seed_20261009','Elevação dos calcanhares para panturrilhas.',ARRAY['Apoie a parte anterior dos pés.','Eleve os calcanhares.','Desça lentamente.'],true),
('Encolhimento com halteres','trapezio','Halteres','iniciante',3,'10-15','60s','fitforge_core_seed_20261009','Elevação escapular para trapézio superior.',ARRAY['Segure halteres ao lado do corpo.','Eleve os ombros verticalmente.','Desça controlando.'],true),
('Caminhada na esteira','cardio','Esteira','iniciante',1,'10-30 min','—','fitforge_core_seed_20261009','Atividade aeróbica de intensidade ajustável.',ARRAY['Comece em velocidade confortável.','Aumente gradualmente conforme tolerância.','Reduza a velocidade antes de descer.'],true)
ON CONFLICT (name, muscle_group) DO NOTHING;
